font_size 16.0
tab_bar_style powerline
tab_powerline_style round
notify_on_cmd_finish unfocused

# BEGIN_KITTY_FONTS
font_family      family="JetBrainsMono Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

# BEGIN_KITTY_THEME
# Ghostty Default
include current-theme.conf
# END_KITTY_THEME
